Deploy script
survival/donation-system-webapp pull request #36
Opened 2018-01-09 12:17 UTC by octopusinvitro

This is something I've been wanting to use for a while. It feels weird not doing this in the terminal, but Sam had a point that doing it through Ruby means people don't have to install extra stuff. Although you may have to install the Heroku CLI.

This PR allows to deploy to staging or production using a rake task. With the Amazon and Heroku credentials in place, deploying is done like this:

```bash
bundle exec rake deploy:staging
```
or
```bash
bundle exec rake deploy:production
```

When deploying, this will happen:
- The `main.css` and `bundle.js` files will be timestamped
- Then they will be uploaded to AWS S3
- Then the timestamped filepaths will be updated in two Heroku env vars
- The application will generate the right path to the files depending if it's running in development, staging or production

I implemented the deployment workflow using 5 different classes:

- **Deploy::FileHelper:** for timestamping the `main.css` and `bundle.js` files
- **Deploy::AmazonFileUploader:** for uploading the timestamped files to a staging or production bucket in AWS S3
- **Deploy::HerokuClient:** for pushing to Heroku staging or Heroku production
- **Deploy::Deployer:** to wire these three up, and to be used in the Rake deploy tasks
- **Helpers::AssetPathsGenerator:** to generate the right path to `main.css` and `bundle.js` in the views, depending if the page is loaded in development, staging or production

From now on, the automatically generated `main.css` and `bundle.js` files will be gitignored .

# Other notes

- The Amazon and Heroku credentials have been uploaded to the credentials repo.
- I also created a new public path `donation-system-webapp` in our Amazon staging and production buckets, with a `css` and a `js` subdirectories
- I installed the `aws-sdk-s3` gem only (the `aws-sdk` gem installs absolutely every Amazon service gem out there).
- I renamed the Heroku `RACK_ENV` environment variable in staging from 'production' to 'staging'

2018-01-23 11:51 UTC, ketan-survival reviewed
Just a query about the parenthesis but the rest LGTM

2018-01-23 11:51 UTC, ketan-survival commented on spec/deploy/heroku_client_spec.rb
> +  describe('when successful') do
why use parenthesis for describe in this file and not for other spec files?

2018-01-23 11:51 UTC, ketan-survival commented on spec/deploy/deployer_spec.rb
> +    describe('when successful') do
This file also has describe with parenthesis.

2018-01-26 12:06 UTC, samstickland requested changes
All pretty minor stuff, I didn't actually get as far as testing the deployment process, because:

a) I don't the heroku rights
b) I wouldn't want to mess up your production or staging instances ;)

```
$ bundle exec rake deploy:staging

--------------------------------------------------------------------------
  ERRORS
--------------------------------------------------------------------------
Missing AWS S3 credentials, bucket not created {:region=>"us-east-1", :access_key_id=>nil, :secret_access_key=>nil}
Missing AWS S3 bucket or it was not created
--------------------------------------------------------------------------

--------------------------------------------------------------------------
  ERRORS
--------------------------------------------------------------------------
Missing AWS S3 credentials, bucket not created {:region=>"us-east-1", :access_key_id=>nil, :secret_access_key=>nil}
Missing AWS S3 bucket or it was not created
--------------------------------------------------------------------------
```

Edit by @octopusinvitro
a) yes you do! I made you admin :slightly_smiling_face: 
b) don't worry about that, it won't be used in a long time until a far away future

2018-01-26 12:06 UTC, samstickland commented on Gemfile
> +gem 'aws-sdk-s3'
Is it worth adding a deployment group that can be skipped when installing on production?

`heroku config:add BUNDLE_WITHOUT="development:test:deployment"`

2018-01-26 12:06 UTC, samstickland commented on lib/deploy/file_helper.rb
> +      today = Time.now.strftime('_%Y-%m-%d_%H-%M-%S')
I think we should use `TIme.now.utc` ?

2018-01-26 12:06 UTC, samstickland commented on lib/deploy/file_helper.rb
> +      today = Time.now.strftime('_%Y-%m-%d_%H-%M-%S')
I'm unsure about using timestamps (as opposed to MD5) for the cache busting. Git doesn't seem to preserve timestamp information.

https://confluence.atlassian.com/bbkb/preserving-file-timestamps-with-git-and-mercurial-781386524.html

I've tested it here by switching between two branches that have a different `spec_helper` and changing the branch is updating the file modification time.

```
~/development/hubbadoproto(system_tests)*$ ls -l spec/rails_helper.rb
-rw-r--r--  1 samuelstickland  staff   5.4K Jan 24 16:05 spec/rails_helper.rb
~/development/hubbadoproto(system_tests)*$ git checkout master
Switched to branch 'master'
Your branch is up-to-date with 'origin/master'.
~/development/hubbadoproto(master)*$ ls -l spec/rails_helper.rb
-rw-r--r--  1 samuelstickland  staff   5.7K Jan 26 11:32 spec/rails_helper.rb
```

Using MD5 should prevent unnecessary generation of new assets.

There are a range of options, but since it doesn't need to be cryptographically secure I think MD5 is fine, and I believe it's also the fastest.

```
sha1 = Digest::SHA1.file file_path
puts "Checksum SHA1: #{sha1.hexdigest}"

sha256 = Digest::SHA256.file file_path
puts "Checksum SHA256: #{sha256.hexdigest}"

sha512 = Digest::SHA512.file file_path
puts "Checksum SHA512: #{sha512.hexdigest}"

md5 = Digest::MD5.file file_path
puts "Checksum MD5: #{md5.hexdigest}"
```

2018-01-26 12:06 UTC, samstickland commented on lib/helpers/asset_paths_generator.rb
> +    def staging_css_path
Is there a reason that these methods aren't also constants (and the hashes above too)?

2018-01-26 12:06 UTC, samstickland commented on spec/deploy/deployer_spec.rb
> +      allow_any_instance_of(FileHelper).to receive(:append_timestamp)
This is only deployment code, so it's not a big problem, but the RSpec team usually consider the `_any_instance_of` methods to be a code smell.

> This feature is sometimes useful when working with legacy code, though in general we
discourage its use for a number of reasons:

> The rspec-mocks API is designed for individual object instances, but this feature operates on entire classes of objects. As a result there are some semantically confusing edge cases. For example, in expect_any_instance_of(Widget).to receive(:name).twice it isn't clear whether a specific instance is expected to receive name twice, or if two receives total are expected. (It's the former.)

> Using this feature is often a design smell. It may be that your test is trying to do too much or that the object under test is too complex.

> It is the most complicated feature of rspec-mocks, and has historically received the most bug reports. (None of the core team actively use it, which doesn't help.)

https://relishapp.com/rspec/rspec-mocks/docs/working-with-legacy-code/any-instance

2018-01-26 12:06 UTC, samstickland commented on spec/spec_helper.rb
> +  config.warnings = false
What is the reason for this change?

2018-01-26 12:06 UTC, samstickland commented on README.md
> +. ./scripts/setup.sh
Minor point, but what's the reason for not having the executable bit set on this file?

2018-01-26 12:06 UTC, samstickland commented on spec/deploy/deployer_spec.rb
> +        expect_any_instance_of(FileHelper).to receive(:append_timestamp)
If you like, because you already have the `allow_any_instance_of` in the `before` block, you could use the more ideomatic test ordering:

```
  deployer.run
  expect_any_instance_of(FileHelper).to have_received(:append_timestamp)
```

2018-01-26 12:21 UTC, octopusinvitro commented on README.md
> +. ./scripts/setup.sh
Yes, that works as well

2018-01-26 12:21 UTC, octopusinvitro commented on Gemfile
> +gem 'aws-sdk-s3'
:+1:

2018-01-26 12:45 UTC, octopusinvitro commented on lib/deploy/file_helper.rb
> +      today = Time.now.strftime('_%Y-%m-%d_%H-%M-%S')
OK, I'll look into this :+1:

2018-01-26 12:47 UTC, octopusinvitro commented on lib/helpers/asset_paths_generator.rb
> +    def staging_css_path
Probably then can be constants, yes

2018-01-26 12:47 UTC, octopusinvitro commented on spec/deploy/deployer_spec.rb
> +      allow_any_instance_of(FileHelper).to receive(:append_timestamp)
:+1:

2018-01-26 12:49 UTC, octopusinvitro commented on spec/spec_helper.rb
> +  config.warnings = false
It's explained in the commit that did the change
https://github.com/survival/donation-system-webapp/pull/36/commits/01adb7116ac8257a5c85fffed59899850cb1f51c

Do you know of a way to disable warnings for a specific gem only

2018-01-26 20:52 UTC, samstickland approved these changes

2018-01-26 21:25 UTC, merged